name: 'Generate Milestone Documentation'
description: 'Generates documentation from milestone definitions'
inputs:
  GITHUB_TOKEN:
    description: 'The GitHub Token'
    required: true
  outputFile:
    description: The file to write the output to
    required: false
    default: MILESTONES.md
  labelMilestonePrefix:
    description: "Prefix of labels that identify a milestone, for example `/cloud` becomes `cloud/M1`. Only effective in combination with `input.orgs`."
    required: false
    default: corp/
  orgs:
    description: "Instead of checking this single repository, also check all the repositories of the given orgs (use comma-separated values - `foo,bar,baz`) for issues with prefixed `labelMilestonePrefix` labels."
    required: false
  ingoreMilestones:
    description: "Ignore milestones with the given names. Ignore multiple milestones with comma-separated values (`foo,bar,baz`)."
    required: false
    default: unplanned
  onlyLabels:
    description: "Only include issues and pull requests with the given labels."
    required: false
    default: bug,feat,blocking,breaking-change,good-first-issue,docs,ci,rfc,help-wanted
runs:
  using: 'node12'
  main: 'index.js'
